parameters:
  gripper_command_only:
    name: "/payload/charger_gripper/gripper_command_only"
    type: "bool"
  gripper_command_interface:
    name: "/payload/charger_gripper/gripper_command_interface"
    type: "string"
  gripper_open_command:
    name: "/payload/charger_gripper/gripper_open_command"
    type: "int"
  gripper_close_command:
    name: "/payload/charger_gripper/gripper_close_command"
    type: "int"
  gripper_command_complete_poll_interval_ms:
    name: "/payload/charger_gripper/gripper_command_complete_poll_interval_ms"
    type: "int"
  gripper_command_complete_timeout_ms:
    name: "/payload/charger_gripper/gripper_command_complete_timeout_ms"
    type: "int"
  charger_gripper_serial_port:
    name: "/payload/charger_gripper/charger_gripper_serial_port"
    type: "string"
  charger_gripper_serial_baudrate:
    name: "/payload/charger_gripper/charger_gripper_serial_baudrate"
    type: "int"
  charger_gripper_serial_timeout:
    name: "/payload/charger_gripper/charger_gripper_serial_timeout"
    type: "float"
  gripper_command_serial_period_ms:
    name: "/payload/charger_gripper/gripper_command_serial_period_ms"
    type: "int"
  charger_gripper_rpi_gpio_pin:
    name: "/payload/charger_gripper/charger_gripper_rpi_gpio_pin"
    type: "int"
  status_timer_period_ms:
    name: "/payload/charger_gripper/status_timer_period_ms"
    type: "int"
  status_message_first_byte:
    name: "/payload/charger_gripper/status_message_first_byte"
    type: "int"
  status_message_last_byte:
    name: "/payload/charger_gripper/status_message_last_byte"
    type: "int"
  status_message_length:
    name: "/payload/charger_gripper/status_message_length"
    type: "int"
  status_message_battery_voltage_start_index:
    name: "/payload/charger_gripper/status_message_battery_voltage_start_index"
    type: "int"
  status_message_battery_voltage_length:
    name: "/payload/charger_gripper/status_message_battery_voltage_length"
    type: "int"
  status_message_charging_power_start_index:
    name: "/payload/charger_gripper/status_message_charging_power_start_index"
    type: "int"
  status_message_charging_power_length:
    name: "/payload/charger_gripper/status_message_charging_power_length"
    type: "int"
  status_message_charger_status_index:
    name: "/payload/charger_gripper/status_message_charger_status_index"
    type: "int"
  status_message_charger_operating_mode_index:
    name: "/payload/charger_gripper/status_message_charger_operating_mode_index"
    type: "int"
  status_message_gripper_status_index:
    name: "/payload/charger_gripper/status_message_gripper_status_index"
    type: "int"
  battery_voltage_avg_filter_size:
    name: "/payload/charger_gripper/battery_voltage_avg_filter_size"
    type: "int"
  charging_power_avg_filter_size:
    name: "/payload/charger_gripper/charging_power_avg_filter_size"
    type: "int"
  