parameters:
  mission_specification_file:
    name: "/mission/mission_specification_file"
    type: "string"
  use_nans_when_hovering:
    name: "/mission/use_nans_when_hovering"
    type: "bool"
  max_failed_attempts_during_maneuver:
    name: "/mission/max_failed_attempts_during_maneuver"
    type: "int"
  wait_for_maneuver_start_timeout_ms:
    name: "/mission/wait_for_maneuver_start_timeout_ms"
    type: "int"
  dt:
    name: "/control/dt"
    type: "float"
  get_reference_timeout_ms:
    name: "/mission/get_reference_timeout_ms"
    type: "int"
  manual_stick_input_threshold:
    name: "/mission/manual_stick_input_threshold"
    type: "float"

parameter_bundles:
  maneuver_reference_client:
    use_nans_when_hovering:
      remap_name: "use_nans_when_hovering"
      update: true
    max_failed_attempts_during_maneuver:
      remap_name: "max_failed_attempts_during_maneuver"
      update: true
    wait_for_maneuver_start_timeout_ms:
      remap_name: "wait_for_maneuver_start_timeout_ms"
      update: true
    get_reference_timeout_ms:
      remap_name: "get_reference_timeout_ms"
      update: true

  mode_provider:
    dt:
      remap_name: "maneuver_setpoint_dt"
      update: false

  mode_executor:
    manual_stick_input_threshold:
      remap_name: "manual_stick_input_threshold"
      update: true

