parameters:
  cli_port:
    name: "/sensor/iwr6843_pcl_pub/cli_port"
    type: "string"
  data_port:
    name: "/sensor/iwr6843_pcl_pub/data_port"
    type: "string"
  cfg_path:
    name: "/sensor/iwr6843_pcl_pub/cfg_path"
    type: "string"
  mmwave_frame_id:
    name: "/tf/mmwave_frame_id"
    type: "string"
  